config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dances#index'

  resources :users, only: [:index, :show] do
    resources :profiles, only: [:new, :create]
  end
  resources :dances do
    resources :dance_comments, only: [:new, :create]
    resources :dance_directions
  end
  resources :dance_comments, except: [:new, :create]
  resources :dance_levels
  resources :formations
  resources :keys
  resources :meters
  resources :moods
  resources :tempos
  resources :comment_types
  resources :profiles, except: [:new, :create]

  namespace :api do
    resources :dance_comments, only: [:create]
    resources :dances, only: [:create, :update]
    resources :dance_directions, only: [:create, :update, :destroy]
    resources :dance_moods, only: [:create, :destroy]
  end
end

app/models/dance_direction.rb
class DanceDirection < ApplicationRecord
  belongs_to :dance

  validates :sequence, presence: true
  validates :movement, presence: true
  validates :dance_id, presence: true
end

app/controllers/api/dance_directions_controller.rb
class Api::DanceDirectionsController < ApplicationController
  # not the best solution, leaves the code open to attack. Use for now, but find a better solution.
  # looks like CSRF token is problem.
  skip_before_action :verify_authenticity_token

  def create
    @dance_direction = DanceDirection.new(dance_direction_params)
    @dance_direction.save

    render json: @dance_direction
  end

  def update
    @dance_direction = DanceDirection.find(dance_direction_params[:id])
    @dance_direction.update(dance_direction_params)

    render json: @dance_direction
  end

  def destroy
    @dance_direction = DanceDirection.find(dance_direction_params[:id])

    @dance_direction.destroy
  end

  private

  def dance_direction_params
    params.require(:dd).permit(
      :id,
      :dance_id,
      :sequence,
      :mark,
      :measure,
      :movement,
      :position
    )
  end
end

app/controllers/dance_directions_controller.rb
class DanceDirectionsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :admin_user?, only: [:show]
  before_action :set_dance_direction, only: [:show, :destroy]

  def show
  end

  def destroy
    @dance_direction.destroy
  end

  private

  def set_dance_direction
    @dance_direction ||= DanceDirection.find(params[:id])
  end

  def dance_direction_params
    params.require(:dance_direction).permit(
      :dance_id,
      :sequence,
      :mark,
      :measure,
      :movement,
      :position
    )
  end
end

app/views/dance_directions/_dance_direction_row.html.erb
<tr class="direction-row">
  <td  class="seq">
    <%= link_to dd.sequence, dance_dance_direction_path(dd.dance_id, dd.id) %>
  </td>

  <td class="mar">
    <% if dd.mark %>
      <%= dd.mark %>
    <% end %>
  </td>

  <td class="mea">
    <% if dd.measure %>
      <%= dd.measure %>
    <% end %>
  </td>

  <td class="dir">
    <%= dd.movement %>
  </td>

  <td class="pos hidden-all">
    <% if dd.position %>
      <%= dd.position %>
    <% end %>
  </td>
</tr>

app/views/dance_directions/_dance_direction_table.html.erb
<table id='dance-directions-table' class='dance-directions-table'>
  <th class="seq header"> </th>
  <th class="mar header">Mark</th>
  <th class="mea header">Measure</th>
  <th class="dir header">Direction</th>
  <th class="pos header hidden-all">Position</th>
  <% dds.each do |dd| %>
    <%= render 'dance_directions/dance_direction_row', dd: dd %>
  <% end %>
</table>

app/views/dance_directions/_form.html.erb
<td class="id hidden-all">
  <input type="text" name="id" value="<%= dd.id %>" >
</td>

<td class="seq hidden-label">
  <label for="sequence">Sequence</label>
  <input type="text" name="sequence" value="<%= dd.sequence %>" required>
</td>

<td class="mar hidden-label">
  <label for="mark">Mark</label>
  <input type="text" name="mark" value="<%= dd.mark %>" >
</td>

<td class="mea hidden-label">
  <label for="measure">Measure</label>
  <input type="text" name="measure" value="<%= dd.measure %>" >
</td>

<td class="dir hidden-label">
  <label for="movement">Direction</label>
  <input type="text" name="movement" value="<%= dd.movement %>" required>
</td>

<td class="pos hidden-label">
  <label for="position">Position</label>
  <input type="text" name="position" value="<%= dd.position %>" >
</td>

<td class="but hidden-label">
  <button type="button" id="dd-remove" class="ref-button">-</button>
</td>

app/views/dance_directions/show.html.erb
<main class="dance-direction-show">
  <h2>
    <%= link_to @dance_direction.dance.title, dance_path(@dance_direction.dance) %>
  </h2>
  <%= render 'dance_direction_table', dds: [@dance_direction] %>
</main>