config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dances#index'

  resources :users, only: [:index, :show] do
    resources :profiles, only: [:new, :create]
  end
  resources :dances do
    resources :dance_comments, only: [:new, :create]
    resources :dance_directions
  end
  resources :dance_comments, except: [:new, :create]
  resources :dance_levels
  resources :formations
  resources :keys
  resources :meters
  resources :moods
  resources :tempos
  resources :comment_types
  resources :profiles, except: [:new, :create]

  namespace :api do
    resources :dance_comments, only: [:create]
    resources :dances, only: [:create, :update]
    resources :dance_directions, only: [:create, :update, :destroy]
    resources :dance_moods, only: [:create, :destroy]
  end
end

app/models/dance_comment.rb
class DanceComment < ApplicationRecord
  belongs_to :user
  belongs_to :dance
  belongs_to :comment_type

  validates :comment, presence: true
  validates :comment_type_id, presence: true
  validates :dance_id, presence: true
  validates :user_id, presence: true

  def creator?(cu)
    cu && cu.id == user_id
  end
end

app/controllers/api/dance_comments_controller.rb
class Api::DanceCommentsController < ApplicationController
  # not the best solution, leaves the code open to attack. Use for now, but find a better solution.
  # looks like CSRF token is problem.
  skip_before_action :verify_authenticity_token

  def create
    @dance_comment = DanceComment.new(dc_params)
    @dance_comment.save

    comment = [@dance_comment,
      user: @dance_comment.user.user_name,
      dance: @dance_comment.dance.title,
      comment_type: @dance_comment.comment_type.name]

    render json: comment
  end

  private

  def dc_params
    params.require(:dance_comment).permit(
      :comment,
      :comment_type_id,
      :user_id,
      :dance_id,
      :comment_id
    )
  end
end

app/controllers/dance_comments_controller.rb
class DanceCommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :admin_user?, only: [:index, :show]
  before_action :dance_comments, only: [:index]
  before_action :set_dance_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_dance, only: [:new, :create]
  before_action :collections, only: [:new, :create, :edit, :update]

  def index
  end

  def show
  end

  def new
    @dance_comment = DanceComment.new
  end

  def create
    @dance_comment = DanceComment.new(
      dance_comment_params.merge(
        user_id: current_user.id,
        dance_id: @dance.id
      )
    )
    if @dance_comment.save
      redirect_to dance_path(@dance)
    else
      flash[:alert] = @dance_comment.errors.full_messages.join(", ")
      redirect_to new_dance_dance_comment_path(@dance)
    end
  end

  def edit
  end

  def update
    if @dance_comment.update(dance_comment_params)
      redirect_to dance_comment_path(@dance_comment)
    else
      flash[:alert] = @dance_comment.errors.full_messages.join(", ")
      redirect_to edit_dance_comment_path(@dance_comment)
    end
  end

  def destroy
    @dance_comment.destroy
    redirect_to dance_path(@dance_comment.dance)
  end

  private

  def set_dance_comment
    @dance_comment ||= DanceComment.find(params[:id])
  end

  def set_dance
    @dance ||= Dance.find(params[:dance_id])
  end

  def collections
    @comment_type_collection ||= CommentType.all.order(:name)
  end

  def dance_comments
    @dance_comments ||= DanceComment.all.order(created_at: :desc)
  end

  def dance_comment_params
    params.require(:dance_comment).permit(
      :comment,
      :user_id,
      :comment_type_id,
      :dance_id
    )
  end
end

app/views/dance_comments/_dance_comment_box.html.erb
<article class="comment-box">
  <h2>
    <%= link_to dc.user.user_name, user_path(dc.user) %> posted a <%= link_to dc.comment_type.name, comment_type_path(dc.comment_type) %> for <%= link_to dc.dance.title, dance_path(dc.dance) %>
  </h2>
  <p><%= link_to dc.comment, dance_comment_path(dc) %></p>

  <footer>
    <ul>
      <% if dc.creator?(current_user) %>
        <li><%= link_to image_tag("icons/svg/pencil.svg", alt:"Edit", title:"Edit", class:"icon"), edit_dance_comment_path(dc), id:"edit-comment" %></li>
      <% end %>
      <% if dc.creator?(current_user) || dc.dance.creator?(current_user) || @admin_user %>
        <li><%= link_to image_tag("icons/svg/trashcan.svg", alt:"Delete", title:"Delete", class:"icon"), dc, method: :delete, data: { confirm: 'Are you sure?' }, :class => "remove-comment", id:"delete-comment" %></li>
      <% end %>
    </ul>
  </footer>
</article>

app/views/dance_comments/_form.html.erb
<%= form_for [@dance, @dance_comment] do |f| %>
  <div id="dcform" class="forms">
    <div class="field">
      <%= f.label :comment_type_id, "Type" %>
      <%= f.collection_select :comment_type_id, @comment_type_collection, :id, :name, required: true %>
      <%= link_to image_tag("icons/svg/question-mark.svg", alt:"Help", title:"Help", class:"help-icon", id:"help-comment-type"), comment_types_path, target: '_blank' %>
    </div>

    <div class="field hidden-label">
      <%= f.label :comment, "Comment" %>
      <%= f.text_area :comment, required: true, placeholder: "Comment..." %>
    </div>

    <div id="actions" class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/dance_comments/edit.html.erb
<main class="dance-comment-edit">
  <h1>Edit your comment.</h1>
  <%= render 'form', dance_comment: @dance_comment %>
</main>

app/views/dance_comments/index.html.erb
<main class="dance-comment-index">
  <header>
    <h1>Dance Comments</h1>
  </header>

  <ul class="dance-comment-list">
    <% @dance_comments.each do |dc| %>
      <li>
        <%= render 'dance_comment_box', dc: dc %>
      </li>
    <% end %>
  </ul>
</main>

app/views/dance_comments/new.html.erb
<main class="dance-comment-new">
  <h1>Create your new comment.</h1>
  <%= render 'form', dance_comment: @dance_comment %>
</main>

app/views/dance_comments/show.html.erb
<main class="dance-comment-show">
  <%= render 'dance_comment_box', dc: @dance_comment %>
</main>