config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dances#index'

  resources :users, only: [:index, :show] do
    resources :profiles, only: [:new, :create]
  end
  resources :dances do
    resources :dance_comments, only: [:new, :create]
    resources :dance_directions
  end
  resources :dance_comments, except: [:new, :create]
  resources :dance_levels
  resources :formations
  resources :keys
  resources :meters
  resources :moods
  resources :tempos
  resources :comment_types
  resources :profiles, except: [:new, :create]

  namespace :api do
    resources :dance_comments, only: [:create]
    resources :dances, only: [:create, :update]
    resources :dance_directions, only: [:create, :update, :destroy]
    resources :dance_moods, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dances
  has_many :dance_comments
  has_one :profile, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :user_name, presence: true, uniqueness: true

  def dances?
    dances != []
  end

  def dance_comments?
    dance_comments != []
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
  before_action :admin_user?
  before_action :users, only: [:index]
  before_action :set_user, only: [:show]
  before_action :set_profile, only: [:show]

  def index
  end

  def show
    @dances ||= list_dances
    @dance_comments ||= list_dcomments
  end

  private

  def users
    @users ||= User.all.order(:user_name)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def list_dances
    @user.dances.order(:title)
  end

  def list_dcomments
    @user.dance_comments.order(created_at: :desc)
  end

  def set_profile
    if @user.profile
      @profile = @user.profile
    else
      @profile = Profile.new(user_id: @user.id)
      @profile.save
    end
  end
end

app/views/users/index.html.erb
<main class="user-index">
  <header>
    <h1>Members</h1>
  </header>

  <ul class="info-list">
    <% @users.each do |user| %>
      <li>
        <article class="user-box">
          <h2><%= link_to user.user_name, user_path(user) %></h2>
        </article>
      </li>
    <% end %>
  </ul>
</main>

app/views/users/show.html.erb
<main class="user-show">
  <header>
    <% if @user == current_user %>
      <ul class="user-bar">
        <li><%= link_to image_tag("icons/svg/user-star.svg", alt:"Edit Profile", title:"Edit Profile", class:"user-icon user-star tooltip"), edit_profile_path(@profile) %></li>
        <li><%= link_to image_tag("icons/svg/user-settings.svg", alt:"Edit Account", title:"Edit Account", class:"user-icon user-settings"), edit_user_registration_path(@user) %></li>
      </ul>
    <% end %>
    <h1><%= @user.user_name %></h1>
  </header>

  <h2>
    <% if @profile.privacy_fn %>
      <%= @user.first_name %>
    <% end %>
    <% if @profile.privacy_ln %>
      <%= @user.last_name %>
    <% end %>
  </h2>

  <h5>
    <% if @profile.privacy_ce %>
      <%= @user.email %>
    <% end %>
  </h5>

  <h6>
    <% if @profile.privacy_lcity %>
      <%= @profile.l_city %>,
    <% end %>
    <% if @profile.privacy_lstate %>
      <%= @profile.l_state %>,
    <% end %>
    <% if @profile.privacy_lcountry %>
      <%= @profile.l_country %>
    <% end %>
  </h6>

  <% if @profile.summary %>
    <fieldset class="ima">
      <% if @profile.ima %>
        <legend>I am a...</legend>
        <div class="badges-box">
          <% if @profile.dancer %>
            <%= image_tag("user_badges/dancer.svg", alt: "Dancer badge", width: "100px") %>
          <% end %>
          <% if @profile.caller %>
          <%= image_tag("user_badges/caller.svg", alt: "Caller badge", width: "100px") %>
          <% end %>
          <% if @profile.musician %>
          <%= image_tag("user_badges/musician.svg", alt: "Musician badge", width: "100px") %>
          <% end %>
          <% if @profile.band %>
          <%= image_tag("user_badges/band.svg", alt: "Band badge", width: "100px") %>
          <% end %>
          <% if @profile.choreographer %>
          <%= image_tag("user_badges/choreographer.svg", alt: "Choreographer badge", width: "100px") %>
          <% end %>
          <% if @profile.composer %>
          <%= image_tag("user_badges/composer.svg", alt: "Composer badge", width: "100px") %>
          <% end %>
        </div>
      <% end %>
      <% if @profile.about %>
        <div class="about">
          <p><%= @profile.about %></p>
        </div>
      <% end %>
    </fieldset>
  <% end %>

  <% if @user.dances? %>
    <section class="dances">
      <h3>Dances</h3>
      <ul class="dance-list">
        <% @dances.each do |dance| %>
        <li>
          <%= render 'dances/dance_box', dance: dance %>
        </li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <% if @user.dance_comments? %>
    <section class="dance-comments">
      <h3>Comments</h3>
      <ul class="dance-comment-list">
        <% @dance_comments.each do |dc| %>
          <li>
            <%= render 'dance_comments/dance_comment_box', dc: dc %>
          </li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <div class="bottom-line">
    <p>Last signed in on <%= @user.last_sign_in_at %></p>
  </div>
</main>