config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dances#index'

  resources :users, only: [:index, :show] do
    resources :profiles, only: [:new, :create]
  end
  resources :dances do
    resources :dance_comments, only: [:new, :create]
    resources :dance_directions
  end
  resources :dance_comments, except: [:new, :create]
  resources :dance_levels
  resources :formations
  resources :keys
  resources :meters
  resources :moods
  resources :tempos
  resources :comment_types
  resources :profiles, except: [:new, :create]

  namespace :api do
    resources :dance_comments, only: [:create]
    resources :dances, only: [:create, :update]
    resources :dance_directions, only: [:create, :update, :destroy]
    resources :dance_moods, only: [:create, :destroy]
  end
end

app/models/dance.rb
class Dance < ApplicationRecord
  belongs_to :user
  belongs_to :meter
  belongs_to :formation
  belongs_to :tempo, optional: true
  belongs_to :key, optional: true
  belongs_to :dance_level, optional: true
  has_many :dance_comments, dependent: :destroy
  has_many :dance_directions, dependent: :destroy
  has_many :dance_moods, dependent: :destroy
  has_many :moods, through: :dance_moods

  validates :title, presence: true, uniqueness: true
  validates :dance_level_id, presence: true
  validates :formation_id, presence: true
  validates :key_id, presence: true
  validates :meter_id, presence: true
  validates :tempo_id, presence: true

  def creator?(cu)
    cu && cu.id == user_id
  end
end

app/controllers/api/dances_controller.rb
class Api::DancesController < ApplicationController
  # not the best solution, leaves the code open to attack. Use for now, but find a better solution.
  # looks like CSRF token is problem.
  skip_before_action :verify_authenticity_token
  
  def create
    @dance = Dance.new(dance_params)
    @dance.save

    render json: @dance
  end

  def update
    @dance = Dance.find(dance_params[:id])
    @dance.update(dance_params)

    render json: @dance
  end

  private

  def dance_params
    params.require(:dance).permit(
      :id,
      :title,
      :choreographer,
      :publication,
      :year,
      :dance_level_id,
      :formation_id,
      :key_id,
      :meter_id,
      :tempo_id,
      :user_id,
    )
  end
end

app/controllers/dances_controller.rb
class DancesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :admin_user?
  before_action :dances, only: [:index]
  before_action :set_dance, only: [:show, :edit, :update, :destroy]
  before_action :moods?, only: [:edit]
  before_action :directions?, only: [:show, :edit]
  before_action :comments?, only: [:show]
  before_action :collections, only: [:show, :new, :create, :edit, :update]
  before_action :new_direction, only: [:new, :edit]

  def index
  end

  def show
    @dance_comment = DanceComment.new
  end

  def new
    @dance = Dance.new
    @dance_direction = DanceDirection.new
  end

  def create
    @dance = Dance.new(dance_params.merge(user_id: current_user.id.to_s))
    if @dance.save
      redirect_to dance_path(@dance.id)
    else
      flash[:alert] = @dance.errors.full_messages.join(", ")
      render new_dance_path
    end
  end

  def edit
  end

  def update
    if @dance.update(dance_params)
      redirect_to dance_path(@dance)
    else
      flash[:alert] = @dance.errors.full_messages.join(", ")
      redirect_to edit_dance_path(@dance)
    end
  end

  def destroy
    if directions?
      @dance.dance_directions.destroy
    end
    if comments?
      @dance.dance_comments.destroy
    end
    @dance.destroy
    redirect_to root_path
  end

  private

  def set_dance
    @dance = Dance.find(params[:id])
  end

  def dances
    @dances ||= Dance.all.order(:title)
  end

  def moods?
    @dance_moods ||= @dance.dance_moods
  end

  def directions?
    @dance_directions ||= @dance.dance_directions.order(:sequence)
  end

  def new_direction
    @dance_direction = DanceDirection.new
  end

  def comments?
    @dance_comments ||= @dance.dance_comments.order(created_at: :desc)
  end

  def collections
    @comment_type_collection ||= CommentType.all.order(:name)
    @formation_collection ||= Formation.all.order(:name)
    @key_collection ||= Key.all.order(:name)
    @level_collection ||= DanceLevel.all
    @meter_collection ||= Meter.all.order(:name)
    @mood_collection ||= Mood.all.order(:name)
    @tempo_collection ||= Tempo.all
  end

  def dance_params
    params.require(:dance).permit(
      :id,
      :title,
      :choreographer,
      :publication,
      :year,
      :dance_level_id,
      :formation_id,
      :key_id,
      :meter_id,
      :tempo_id,
      :user_id
    )
  end
end

app/views/dances/_dance_box.html.erb
<article class="dance-box">
  <section>
    <h1><%= link_to dance.title, dance_path(dance) %>
      <% if dance.year %>
        <bdi>(<%= dance.year %>)</bdi>
      <% end %>
    </h1>
  </section>

  <section>
    <!-- the name of the song -->
  </section>

  <section class='dance-info-preview'>
      <table class='dance-info'>
        <tr>
          <% if dance.dance_directions %>
            <%= render 'dance_directions/dance_direction_table', dance: dance, dds: dance.dance_directions.order(:sequence).limit(3) %>
          <% end %>
          <tr>
            <%= link_to image_tag("icons/svg/029-mark.svg", alt:"More", title:"More", class:"icon"), dance_path(dance) %>
          </tr>
        </tr>
      </table>
  </section>

  <section>
    <% if dance.choreographer && dance.choreographer != "" %>
      <p><bdi>Choreographed by:</bdi> <%= dance.choreographer %></p>
    <% end %>
    <p><bdi>Created by:</bdi> <%= link_to dance.user.user_name, user_path(dance.user_id) %></p>
  </section>

  <footer>
    <ul>
      <% if dance.creator?(current_user) %>
        <li><%= link_to image_tag("icons/svg/pencil.svg", alt:"Edit", title:"Edit",
        class:"icon"), edit_dance_path(dance) %></li>
      <% end %>
      <% if dance.creator?(current_user) || @admin_user %>
        <li><%= link_to image_tag("icons/svg/trashcan.svg", alt:"Delete", title:"Delete", class:"icon"), dance, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <% end %>
    </ul>
  </footer>
</article>

app/views/dances/_form.html.erb
<%= form_for @dance do |f| %>
  <div id="forms" class="forms" spellcheck="true">
    <form id="d-dd-form">

      <div class="d-info-field left">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, required: true %>
      </div>

      <div class="d-info-field right year">
        <%= f.label :year, "Year" %>
        <%= f.text_field :year %>
      </div>

      <div class="d-info-field left chor">
        <%= f.label :choreographer, "Choreographer" %>
        <%= f.text_field :choreographer %>
      </div>

      <div class="d-info-field right pub">
        <%= f.label :publication, "Publication" %>
        <%= f.text_field :publication %>
      </div>

      <div class="d-info-field left">
        <%= f.label :formation_id, "Formation" %>
        <%= f.collection_select :formation_id, @formation_collection, :id, :name, required: true %>
        <%= link_to image_tag("icons/svg/question-mark.svg", alt:"Help", title:"Help", class:"help-icon"), formations_path, target: '_blank' %>
      </div>

      <div class="d-info-field right">
        <%= f.label :meter_id, "Meter" %>
        <%= f.collection_select :meter_id, @meter_collection, :id, :name, required: true %>
        <%= link_to image_tag("icons/svg/question-mark.svg", alt:"Help", title:"Help", class:"help-icon"), meters_path, target: '_blank' %>
      </div>

      <!-- Eventually need to be able to select blank as an option as these fields are not required -->
      <div class="d-info-field left">
        <%= f.label :key_id, "Key" %>
        <%= f.collection_select :key_id, @key_collection, :id, :name %>
        <%= link_to image_tag("icons/svg/question-mark.svg", alt:"Help", title:"Help", class:"help-icon"), keys_path, target: '_blank' %>
      </div>

      <div class="d-info-field right">
        <%= f.label :tempo_id, "Tempo" %>
        <%= f.collection_select :tempo_id, @tempo_collection, :id, :name %>
        <%= link_to image_tag("icons/svg/question-mark.svg", alt:"Help", title:"Help", class:"help-icon"), tempos_path, target: '_blank' %>
      </div>

      <!-- Eventually want to be able to select one from a list of radio buttons rather than drop down. -->
      <div class="d-info-field">
        <%= f.label :dance_level_id, "Level" %>
        <%= f.collection_select :dance_level_id, @level_collection, :id, :name %>
        <%= link_to image_tag("icons/svg/question-mark.svg", alt:"Help", title:"Help", class:"help-icon"), dance_levels_path, target: '_blank' %>
      </div>

      <!-- Eventually need to be able to select multiple MOODS from a list of radio buttons rather than drop down -->
      <div id="moods-ids">
        <%= f.label :mood_ids, "Mood" %>
        <%= f.collection_check_boxes(:mood_ids, @mood_collection, :id, :name) %>
      </div>

      <table>
        <tr>
          <table class="no-bord">
            <tr>
              <td>
                <label>Directions</label>
              </td>
            </tr>
          </table>
        </tr>

        <tr>
          <table id="dd-form" class="dd-form">
            <tr>
              <th class="hidden-label">
                <label for="sequence" class="seq">Sequence</label>
              </th>
              <th>
                <label for="mark" class="mar">Mark</label>
              </th>
              <th>
                <label for="measure" class="mea">Measure</label>
              <th>
                <label for="direction" class="dir">Movement</label>
              <th>
                <label for="position" class="pos">Position</label>
              </th>
              <th>
                <label for="icons" class="but hidden"></label>
              </th>
            </tr>
            <section id="dd-editable-list">
              <% if @dance_directions %>
                <% @dance_directions.each do |dd| %>
                  <tr class="dd-editable">
                    <%= render 'dance_directions/form', dd: dd %>
                  </tr>
                <% end %>
              <% end %>
            </section>
            <section id="dd-new-list">
            </section>
          </table>
        </table>

        <button type="button" id="dd-add" class="ref-button">+</button>
        <p class="actions"><%= f.submit %></p>
    </form>
  </div>
<% end %>

app/views/dances/edit.html.erb
<main id="dance-edit" class="dance-edit">
  <h1>Edit <%= @dance.title %></h1>
  <p id='dance-id' class='hidden-all'><%= @dance.id %></p>

  <!-- Dance Moods IDs -->
  <ul id='dance-mood-ids' class='hidden-all'>
    <% @dance_moods.each do |m| %>
      <li><%= m.mood_id %>, <%= m.id %></li>
    <% end %>
  </ul>

  <%= render 'form', dance: @dance, dance_direction: @dance_direction %>
</main>

app/views/dances/index.html.erb
<main class="dance-index">
  <header class="user-bar">
    <ul class="admin-bar">
      <li><%= link_to image_tag("icons/svg/create-new-dance.svg", alt:"Create a Dance", title:"Create a Dance", class:"user-icon"), new_dance_path %></li>
    </ul>
    <h1>Dance List</h1>
  </header>

  <ul class="dance-list">
    <% @dances.each do |dance| %>
      <li>
        <%= render 'dance_box', dance: dance %>
      </li>
    <% end %>
  </ul>
</main>

app/views/dances/new.html.erb
<main id="dance-new" class="dance-new">
  <h1>Create your new dance.</h1>
  <div class='warning'>
    <p>You, the user, are responsible for knowing if a dance is free to share before posting it to the site. My Terpsichore takes no responsiblity for the posting of copyrighted or trademarked information.</p>
  </div>
  <%= render 'form', dance: @dance, dance_direction: @dance_direction %>
</main>

app/views/dances/show.html.erb
<main id='dance-show' class='dance-show'>
  <header>
    <ul class='user-bar'>
      <% if @dance.creator?(current_user) || @admin_user %>
        <li><%= link_to image_tag("icons/svg/trashcan.svg", alt:"Delete", title:"Delete", class:"icon"), @dance, method: :delete, data: { confirm: 'Are you sure?' }, id:"delete-dance" %></li>
        <li><%= link_to image_tag("icons/svg/pencil.svg", alt:"Edit", title:"Edit",
        class:"icon"), edit_dance_path(@dance), id:"edit-dance" %></li>
      <% end %>
      <li>Created by: <%= link_to @dance.user.user_name, user_path(@dance.user_id) %></li>
    </ul>
    <p id='dance-id' class='hidden-all'><%= @dance.id %></p>

    <h1><%= @dance.title %>
      <% if @dance.year %>
        <bdi>(<%= @dance.year %>)</bdi>
      <% end %>
    </h1>
  </header>

  <div class="d-info-field left">
    <h6>Formation: </h6>
    <p><%= link_to @dance.formation.name, formation_path(@dance.formation) %></p>
  </div>

  <div class="d-info-field right">
    <h6>Meter: </h6>
    <p><%= link_to @dance.meter.name, meter_path(@dance.meter) %></p>
  </div>

  <% if @dance.tempo && @dance.tempo != "" %>
    <div class="d-info-field left">
      <h6>Tempo: </h6>
      <p><%= link_to @dance.tempo.name, tempo_path(@dance.tempo) %></p>
    </div>
  <% end %>

  <% if @dance.key && @dance.key != "" %>
    <div class="d-info-field right">
      <h6>Key: </h6>
      <p><%= link_to @dance.key.name, key_path(@dance.key) %></p>
    </div>
  <% end %>

  <% if @dance.dance_level && @dance.dance_level != "" %>
    <div class="d-info-field left">
      <h6>Level: </h6>
      <p><%= link_to @dance.dance_level.name, dance_level_path(@dance.dance_level) %></p>
    </div>
  <% end %>

  <% if @dance.moods && @dance.moods != "" && @dance.moods != [] %>
    <div class="d-info-field right">
      <h6>Moods: </h6>
      <p> <%= @dance.moods.map{|m| m.name}.join(', ') %> </p>
    </div>
  <% end %>

  <% if @dance.choreographer && @dance.choreographer != "" %>
    <div class="d-info-field left">
      <h6>Choreographer: </h6>
      <p><%= @dance.choreographer %></p>
    </div>
  <% end %>

  <% if @dance.publication && @dance.publication != "" %>
    <div class="d-info-field right">
      <h6>Publication: </h6>
      <p><%= @dance.publication %></p>
    </div>
  <% end %>


  <table class='dance-info'>
    <tr>
      <td>
        <h6>Directions</h6>
      </td>
      <td></td>
      <% if @dance.dance_directions %>
        <%= render 'dance_directions/dance_direction_table', dance: @dance, dds: @dance_directions %>
      <% end %>
    </tr>
  </table>

  <section id='comments' class='comments'>
    <header>
      <h2>Comments</h2>
      <%= link_to 'Create Comment', new_dance_dance_comment_path(@dance) %>
      <% if current_user %>
        <form id='dc-form'>
          <%= render 'dance_comments/form', dance: @dance, dance_comment: @dance_comment %>
        </form>
      <% end %>
    </header>

    <% if @dance.dance_comments %>
      <ul id='dance-comment-list' class='dance-comment-list'>
        <% @dance_comments.each do |dc| %>
          <li>
            <%= render 'dance_comments/dance_comment_box', dc: dc %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </section>
</main>